"""Expanded RAG answer evaluation; preserves the original 30-question script.
Questions are synthetic candidates and require manual legal review.
Source matching and automated groundedness are not proof of answer correctness.
"""
import csv
import time
from pathlib import Path
from rag_engine import LegalRAGEngine

TESTS = [
    ('Explain Article 12 and the definition of the State with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain equality before the law under Article 14 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain prohibition of discrimination under Article 15 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain equality of opportunity in public employment under Article 16 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain abolition of untouchability under Article 17 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain abolition of titles under Article 18 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain freedom of speech and expression under Article 19 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain protection in respect of conviction for offences under Article 20 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain protection of life and personal liberty under Article 21 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain right to education under Article 21A with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain protection against arrest and detention under Article 22 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain prohibition of human trafficking under Article 23 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain prohibition of child labour under Article 24 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain freedom of conscience under Article 25 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain freedom to manage religious affairs under Article 26 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain freedom from certain taxes for religious promotion under Article 27 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain freedom from religious instruction in certain institutions under Article 28 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain protection of cultural rights under Article 29 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain minority educational institutions under Article 30 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain constitutional remedies under Article 32 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain abolition of titles and constitutional equality with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain Fundamental Duties under Article 51A with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain Directive Principles of State Policy with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain organisation of village panchayats under Article 40 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain uniform civil code under Article 44 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain protection of environment under Article 48A with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain separation of judiciary and executive under Article 50 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain definition and scope of the Union executive with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain constitutional position of the President of India with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain election of the President with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain powers and functions of the President with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain appointment and role of the Vice-President with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain appointment of the Prime Minister with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain collective responsibility of the Council of Ministers with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain composition of the Council of States with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain composition of the House of the People with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain qualification for membership of Parliament with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain duration of the Houses of Parliament with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain powers of the Speaker of the Lok Sabha with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain ordinary legislative procedure in Parliament with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain joint sitting of Parliament with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain money bills and their procedure with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain annual financial statement and the Union Budget with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain ordinance-making power of the President with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain Supreme Court original jurisdiction with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain Supreme Court appellate jurisdiction with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain advisory jurisdiction of the Supreme Court with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain writ jurisdiction of High Courts with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain independence of the judiciary with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain appointment of Supreme Court judges with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain appointment of High Court judges with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain judicial review under the Constitution with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain powers of the Governor with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain appointment of the Chief Minister with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain State Council of Ministers with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain composition of State Legislatures with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain legislative powers of States with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain distribution of legislative powers between Union and States with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain Union List in the Seventh Schedule with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain State List in the Seventh Schedule with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain Concurrent List in the Seventh Schedule with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain residuary legislative powers with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain administrative relations between Union and States with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain financial relations between Union and States with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain Finance Commission under Article 280 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain Election Commission under Article 324 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain Comptroller and Auditor General of India with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain Public Service Commissions with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain constitutional amendment procedure under Article 368 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain national emergency under Article 352 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ("Explain President's Rule under Article 356 with reference to the Constitution of India.", 'constitution_of_india.pdf'),
    ('Explain financial emergency under Article 360 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain official language provisions with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain citizenship provisions in the Constitution with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain territory of India under Article 1 with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain admission and establishment of new States with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain protection of property under Article 300A with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain constitutional protection for civil servants with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain reservation provisions in the Constitution with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain special provisions for certain States with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain scheduled areas and tribal areas with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain panchayats under Part IX with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain municipalities under Part IXA with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain co-operative societies under Part IXB with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain anti-defection provisions in the Tenth Schedule with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain disqualification of members of Parliament with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain constitutional privileges of Parliament with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain constitutional privileges of State Legislatures with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain provisions concerning elections with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain bar to court interference in electoral matters with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain tribunals under Articles 323A and 323B with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain official language of the Union with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain special provisions for linguistic minorities with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain constitutional duties of the Union with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain constitutional duties of States with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain preamble and its constitutional significance with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain basic structure doctrine with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain constitutional limits on legislative power with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain relationship between Fundamental Rights and Directive Principles with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain constitutional safeguards during emergencies with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain constitutional provisions governing public finance with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('Explain constitutional provisions for scheduled castes and tribes with reference to the Constitution of India.', 'constitution_of_india.pdf'),
    ('What does Article 12 and the definition of the State provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs Article 12 and the definition of the State?', 'constitution_of_india.pdf'),
    ('How does Article 12 and the definition of the State operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is Article 12 and the definition of the State constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of Article 12 and the definition of the State?', 'constitution_of_india.pdf'),
    ('What does equality before the law under Article 14 provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs equality before the law under Article 14?', 'constitution_of_india.pdf'),
    ('How does equality before the law under Article 14 operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is equality before the law under Article 14 constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of equality before the law under Article 14?', 'constitution_of_india.pdf'),
    ('What does prohibition of discrimination under Article 15 provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs prohibition of discrimination under Article 15?', 'constitution_of_india.pdf'),
    ('How does prohibition of discrimination under Article 15 operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is prohibition of discrimination under Article 15 constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of prohibition of discrimination under Article 15?', 'constitution_of_india.pdf'),
    ('What does equality of opportunity in public employment under Article 16 provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs equality of opportunity in public employment under Article 16?', 'constitution_of_india.pdf'),
    ('How does equality of opportunity in public employment under Article 16 operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is equality of opportunity in public employment under Article 16 constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of equality of opportunity in public employment under Article 16?', 'constitution_of_india.pdf'),
    ('What does abolition of untouchability under Article 17 provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs abolition of untouchability under Article 17?', 'constitution_of_india.pdf'),
    ('How does abolition of untouchability under Article 17 operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is abolition of untouchability under Article 17 constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of abolition of untouchability under Article 17?', 'constitution_of_india.pdf'),
    ('What does abolition of titles under Article 18 provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs abolition of titles under Article 18?', 'constitution_of_india.pdf'),
    ('How does abolition of titles under Article 18 operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is abolition of titles under Article 18 constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of abolition of titles under Article 18?', 'constitution_of_india.pdf'),
    ('What does freedom of speech and expression under Article 19 provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs freedom of speech and expression under Article 19?', 'constitution_of_india.pdf'),
    ('How does freedom of speech and expression under Article 19 operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is freedom of speech and expression under Article 19 constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of freedom of speech and expression under Article 19?', 'constitution_of_india.pdf'),
    ('What does protection in respect of conviction for offences under Article 20 provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs protection in respect of conviction for offences under Article 20?', 'constitution_of_india.pdf'),
    ('How does protection in respect of conviction for offences under Article 20 operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is protection in respect of conviction for offences under Article 20 constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of protection in respect of conviction for offences under Article 20?', 'constitution_of_india.pdf'),
    ('What does protection of life and personal liberty under Article 21 provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs protection of life and personal liberty under Article 21?', 'constitution_of_india.pdf'),
    ('How does protection of life and personal liberty under Article 21 operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is protection of life and personal liberty under Article 21 constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of protection of life and personal liberty under Article 21?', 'constitution_of_india.pdf'),
    ('What does right to education under Article 21A provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs right to education under Article 21A?', 'constitution_of_india.pdf'),
    ('How does right to education under Article 21A operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is right to education under Article 21A constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of right to education under Article 21A?', 'constitution_of_india.pdf'),
    ('What does protection against arrest and detention under Article 22 provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs protection against arrest and detention under Article 22?', 'constitution_of_india.pdf'),
    ('How does protection against arrest and detention under Article 22 operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is protection against arrest and detention under Article 22 constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of protection against arrest and detention under Article 22?', 'constitution_of_india.pdf'),
    ('What does prohibition of human trafficking under Article 23 provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs prohibition of human trafficking under Article 23?', 'constitution_of_india.pdf'),
    ('How does prohibition of human trafficking under Article 23 operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is prohibition of human trafficking under Article 23 constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of prohibition of human trafficking under Article 23?', 'constitution_of_india.pdf'),
    ('What does prohibition of child labour under Article 24 provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs prohibition of child labour under Article 24?', 'constitution_of_india.pdf'),
    ('How does prohibition of child labour under Article 24 operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is prohibition of child labour under Article 24 constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of prohibition of child labour under Article 24?', 'constitution_of_india.pdf'),
    ('What does freedom of conscience under Article 25 provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs freedom of conscience under Article 25?', 'constitution_of_india.pdf'),
    ('How does freedom of conscience under Article 25 operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is freedom of conscience under Article 25 constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of freedom of conscience under Article 25?', 'constitution_of_india.pdf'),
    ('What does freedom to manage religious affairs under Article 26 provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs freedom to manage religious affairs under Article 26?', 'constitution_of_india.pdf'),
    ('How does freedom to manage religious affairs under Article 26 operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is freedom to manage religious affairs under Article 26 constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of freedom to manage religious affairs under Article 26?', 'constitution_of_india.pdf'),
    ('What does freedom from certain taxes for religious promotion under Article 27 provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs freedom from certain taxes for religious promotion under Article 27?', 'constitution_of_india.pdf'),
    ('How does freedom from certain taxes for religious promotion under Article 27 operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is freedom from certain taxes for religious promotion under Article 27 constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of freedom from certain taxes for religious promotion under Article 27?', 'constitution_of_india.pdf'),
    ('What does freedom from religious instruction in certain institutions under Article 28 provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs freedom from religious instruction in certain institutions under Article 28?', 'constitution_of_india.pdf'),
    ('How does freedom from religious instruction in certain institutions under Article 28 operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is freedom from religious instruction in certain institutions under Article 28 constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of freedom from religious instruction in certain institutions under Article 28?', 'constitution_of_india.pdf'),
    ('What does protection of cultural rights under Article 29 provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs protection of cultural rights under Article 29?', 'constitution_of_india.pdf'),
    ('How does protection of cultural rights under Article 29 operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is protection of cultural rights under Article 29 constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of protection of cultural rights under Article 29?', 'constitution_of_india.pdf'),
    ('What does minority educational institutions under Article 30 provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs minority educational institutions under Article 30?', 'constitution_of_india.pdf'),
    ('How does minority educational institutions under Article 30 operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is minority educational institutions under Article 30 constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of minority educational institutions under Article 30?', 'constitution_of_india.pdf'),
    ('What does constitutional remedies under Article 32 provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs constitutional remedies under Article 32?', 'constitution_of_india.pdf'),
    ('How does constitutional remedies under Article 32 operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is constitutional remedies under Article 32 constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of constitutional remedies under Article 32?', 'constitution_of_india.pdf'),
    ('What does abolition of titles and constitutional equality provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs abolition of titles and constitutional equality?', 'constitution_of_india.pdf'),
    ('How does abolition of titles and constitutional equality operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is abolition of titles and constitutional equality constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of abolition of titles and constitutional equality?', 'constitution_of_india.pdf'),
    ('What does Fundamental Duties under Article 51A provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs Fundamental Duties under Article 51A?', 'constitution_of_india.pdf'),
    ('How does Fundamental Duties under Article 51A operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is Fundamental Duties under Article 51A constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of Fundamental Duties under Article 51A?', 'constitution_of_india.pdf'),
    ('What does Directive Principles of State Policy provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs Directive Principles of State Policy?', 'constitution_of_india.pdf'),
    ('How does Directive Principles of State Policy operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is Directive Principles of State Policy constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of Directive Principles of State Policy?', 'constitution_of_india.pdf'),
    ('What does organisation of village panchayats under Article 40 provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs organisation of village panchayats under Article 40?', 'constitution_of_india.pdf'),
    ('How does organisation of village panchayats under Article 40 operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is organisation of village panchayats under Article 40 constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of organisation of village panchayats under Article 40?', 'constitution_of_india.pdf'),
    ('What does uniform civil code under Article 44 provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs uniform civil code under Article 44?', 'constitution_of_india.pdf'),
    ('How does uniform civil code under Article 44 operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is uniform civil code under Article 44 constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of uniform civil code under Article 44?', 'constitution_of_india.pdf'),
    ('What does protection of environment under Article 48A provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs protection of environment under Article 48A?', 'constitution_of_india.pdf'),
    ('How does protection of environment under Article 48A operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is protection of environment under Article 48A constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of protection of environment under Article 48A?', 'constitution_of_india.pdf'),
    ('What does separation of judiciary and executive under Article 50 provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs separation of judiciary and executive under Article 50?', 'constitution_of_india.pdf'),
    ('How does separation of judiciary and executive under Article 50 operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is separation of judiciary and executive under Article 50 constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of separation of judiciary and executive under Article 50?', 'constitution_of_india.pdf'),
    ('What does definition and scope of the Union executive provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs definition and scope of the Union executive?', 'constitution_of_india.pdf'),
    ('How does definition and scope of the Union executive operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is definition and scope of the Union executive constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of definition and scope of the Union executive?', 'constitution_of_india.pdf'),
    ('What does constitutional position of the President of India provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs constitutional position of the President of India?', 'constitution_of_india.pdf'),
    ('How does constitutional position of the President of India operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Why is constitutional position of the President of India constitutionally significant?', 'constitution_of_india.pdf'),
    ('What are the key features of constitutional position of the President of India?', 'constitution_of_india.pdf'),
    ('What does election of the President provide?', 'constitution_of_india.pdf'),
    ('Which constitutional provision governs election of the President?', 'constitution_of_india.pdf'),
    ('How does election of the President operate under the Constitution?', 'constitution_of_india.pdf'),
    ('Explain definition of a consumer under Section 2 under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain definition of a complaint under Section 2 under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain meaning of a defect in goods under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain meaning of deficiency in services under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain meaning of an unfair trade practice under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain meaning of a restrictive trade practice under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain meaning of an unfair contract under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain definition of product liability under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain product liability of a manufacturer under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain product liability of a product seller under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain product liability of a product service provider under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain consumer rights recognised by the Act under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain scope and objectives of the Consumer Protection Act, 2019 under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain Central Consumer Protection Authority under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain powers of the Central Consumer Protection Authority under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain investigation of consumer rights violations under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain recall of unsafe goods under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain discontinuation of unfair practices under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain orders concerning misleading advertisements under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain endorsements in advertisements under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain penalties relating to misleading advertisements under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain consumer dispute redressal commissions under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain jurisdiction of the District Commission under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain jurisdiction of the State Commission under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain jurisdiction of the National Commission under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain filing a consumer complaint under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain who may file a consumer complaint under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain electronic filing of consumer complaints under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain territorial jurisdiction for complaints under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain pecuniary jurisdiction of consumer commissions under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain limitation period for consumer complaints under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain admission of consumer complaints under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain procedure after admission of a complaint under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain laboratory testing of defective goods under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain complaints involving services under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain complaints involving unfair trade practices under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain complaints involving overcharging under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain complaints involving hazardous goods under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain complaints involving hazardous services under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain consumer mediation under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain referral of disputes to mediation under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain consumer mediation cells under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain settlement through mediation under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain orders available to consumer commissions under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain removal of defects in goods under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain replacement of defective goods under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain refund of the price paid under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain compensation for loss or injury under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain discontinuation of unfair trade practices under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain withdrawal of hazardous goods under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain corrective advertisements under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain costs awarded in consumer disputes under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain appeals from District Commission orders under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain appeals from State Commission orders under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain appeals to the National Commission under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain appeals to the Supreme Court under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain enforcement of consumer commission orders under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain penalties for failure to comply with orders under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain offences relating to adulterated products under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain offences relating to spurious goods under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain product liability actions under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain exceptions to product liability under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain responsibilities of product manufacturers under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain responsibilities of product sellers under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain responsibilities of product service providers under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain unfair contracts and consumer remedies under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain misleading representations about goods under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain false descriptions of services under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain false guarantees about products under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain e-commerce under the Consumer Protection Act under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain duties of e-commerce entities under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain consumer complaints against online marketplaces under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain consumer protection in online transactions under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain direct selling under consumer protection rules under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain consumer protection in electronic sales under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain consumer protection rules for online shopping under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain advertising claims and consumer rights under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain endorser liability for misleading advertisements under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain investigation powers of the CCPA under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain search and seizure powers under the Act under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain consumer awareness and education under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain consumer councils under the Act under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain Central Consumer Protection Council under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain State Consumer Protection Council under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain District Consumer Protection Council under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain consumer dispute resolution procedures under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain rights of consumers in defective-product cases under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain rights of consumers in deficient-service cases under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain relief available for unfair trade practices under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain complaints about excess prices under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain complaints about unsafe products under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain complaints about product liability under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain responsibility for misleading advertisements under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain consumer disputes involving warranties under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain consumer protection for digital purchases under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain consumer remedies for delayed delivery under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain consumer disputes involving online payments under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain consumer complaints involving service providers under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain consumer complaints involving manufacturers under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain consumer complaints involving retailers under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain review of consumer commission orders under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain appeal procedure under the Act under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('Explain alternative dispute resolution in consumer matters under the Consumer Protection Act, 2019.', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about definition of a consumer under Section 2?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs definition of a consumer under Section 2?', 'consumer_protection_act_2019.pdf'),
    ('How is definition of a consumer under Section 2 addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to definition of a consumer under Section 2?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of definition of a consumer under Section 2 under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about definition of a complaint under Section 2?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs definition of a complaint under Section 2?', 'consumer_protection_act_2019.pdf'),
    ('How is definition of a complaint under Section 2 addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to definition of a complaint under Section 2?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of definition of a complaint under Section 2 under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about meaning of a defect in goods?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs meaning of a defect in goods?', 'consumer_protection_act_2019.pdf'),
    ('How is meaning of a defect in goods addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to meaning of a defect in goods?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of meaning of a defect in goods under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about meaning of deficiency in services?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs meaning of deficiency in services?', 'consumer_protection_act_2019.pdf'),
    ('How is meaning of deficiency in services addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to meaning of deficiency in services?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of meaning of deficiency in services under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about meaning of an unfair trade practice?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs meaning of an unfair trade practice?', 'consumer_protection_act_2019.pdf'),
    ('How is meaning of an unfair trade practice addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to meaning of an unfair trade practice?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of meaning of an unfair trade practice under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about meaning of a restrictive trade practice?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs meaning of a restrictive trade practice?', 'consumer_protection_act_2019.pdf'),
    ('How is meaning of a restrictive trade practice addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to meaning of a restrictive trade practice?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of meaning of a restrictive trade practice under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about meaning of an unfair contract?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs meaning of an unfair contract?', 'consumer_protection_act_2019.pdf'),
    ('How is meaning of an unfair contract addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to meaning of an unfair contract?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of meaning of an unfair contract under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about definition of product liability?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs definition of product liability?', 'consumer_protection_act_2019.pdf'),
    ('How is definition of product liability addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to definition of product liability?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of definition of product liability under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about product liability of a manufacturer?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs product liability of a manufacturer?', 'consumer_protection_act_2019.pdf'),
    ('How is product liability of a manufacturer addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to product liability of a manufacturer?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of product liability of a manufacturer under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about product liability of a product seller?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs product liability of a product seller?', 'consumer_protection_act_2019.pdf'),
    ('How is product liability of a product seller addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to product liability of a product seller?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of product liability of a product seller under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about product liability of a product service provider?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs product liability of a product service provider?', 'consumer_protection_act_2019.pdf'),
    ('How is product liability of a product service provider addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to product liability of a product service provider?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of product liability of a product service provider under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about consumer rights recognised by the Act?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs consumer rights recognised by the Act?', 'consumer_protection_act_2019.pdf'),
    ('How is consumer rights recognised by the Act addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to consumer rights recognised by the Act?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of consumer rights recognised by the Act under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about scope and objectives of the Consumer Protection Act, 2019?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs scope and objectives of the Consumer Protection Act, 2019?', 'consumer_protection_act_2019.pdf'),
    ('How is scope and objectives of the Consumer Protection Act, 2019 addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to scope and objectives of the Consumer Protection Act, 2019?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of scope and objectives of the Consumer Protection Act, 2019 under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about Central Consumer Protection Authority?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs Central Consumer Protection Authority?', 'consumer_protection_act_2019.pdf'),
    ('How is Central Consumer Protection Authority addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to Central Consumer Protection Authority?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of Central Consumer Protection Authority under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about powers of the Central Consumer Protection Authority?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs powers of the Central Consumer Protection Authority?', 'consumer_protection_act_2019.pdf'),
    ('How is powers of the Central Consumer Protection Authority addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to powers of the Central Consumer Protection Authority?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of powers of the Central Consumer Protection Authority under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about investigation of consumer rights violations?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs investigation of consumer rights violations?', 'consumer_protection_act_2019.pdf'),
    ('How is investigation of consumer rights violations addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to investigation of consumer rights violations?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of investigation of consumer rights violations under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about recall of unsafe goods?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs recall of unsafe goods?', 'consumer_protection_act_2019.pdf'),
    ('How is recall of unsafe goods addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to recall of unsafe goods?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of recall of unsafe goods under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about discontinuation of unfair practices?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs discontinuation of unfair practices?', 'consumer_protection_act_2019.pdf'),
    ('How is discontinuation of unfair practices addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to discontinuation of unfair practices?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of discontinuation of unfair practices under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about orders concerning misleading advertisements?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs orders concerning misleading advertisements?', 'consumer_protection_act_2019.pdf'),
    ('How is orders concerning misleading advertisements addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to orders concerning misleading advertisements?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of orders concerning misleading advertisements under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about endorsements in advertisements?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs endorsements in advertisements?', 'consumer_protection_act_2019.pdf'),
    ('How is endorsements in advertisements addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to endorsements in advertisements?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of endorsements in advertisements under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about penalties relating to misleading advertisements?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs penalties relating to misleading advertisements?', 'consumer_protection_act_2019.pdf'),
    ('How is penalties relating to misleading advertisements addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to penalties relating to misleading advertisements?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of penalties relating to misleading advertisements under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about consumer dispute redressal commissions?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs consumer dispute redressal commissions?', 'consumer_protection_act_2019.pdf'),
    ('How is consumer dispute redressal commissions addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to consumer dispute redressal commissions?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of consumer dispute redressal commissions under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about jurisdiction of the District Commission?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs jurisdiction of the District Commission?', 'consumer_protection_act_2019.pdf'),
    ('How is jurisdiction of the District Commission addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to jurisdiction of the District Commission?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of jurisdiction of the District Commission under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about jurisdiction of the State Commission?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs jurisdiction of the State Commission?', 'consumer_protection_act_2019.pdf'),
    ('How is jurisdiction of the State Commission addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to jurisdiction of the State Commission?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of jurisdiction of the State Commission under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about jurisdiction of the National Commission?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs jurisdiction of the National Commission?', 'consumer_protection_act_2019.pdf'),
    ('How is jurisdiction of the National Commission addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to jurisdiction of the National Commission?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of jurisdiction of the National Commission under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about filing a consumer complaint?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs filing a consumer complaint?', 'consumer_protection_act_2019.pdf'),
    ('How is filing a consumer complaint addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to filing a consumer complaint?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of filing a consumer complaint under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about who may file a consumer complaint?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs who may file a consumer complaint?', 'consumer_protection_act_2019.pdf'),
    ('How is who may file a consumer complaint addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to who may file a consumer complaint?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of who may file a consumer complaint under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about electronic filing of consumer complaints?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs electronic filing of consumer complaints?', 'consumer_protection_act_2019.pdf'),
    ('How is electronic filing of consumer complaints addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to electronic filing of consumer complaints?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of electronic filing of consumer complaints under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about territorial jurisdiction for complaints?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs territorial jurisdiction for complaints?', 'consumer_protection_act_2019.pdf'),
    ('How is territorial jurisdiction for complaints addressed under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What legal remedies relate to territorial jurisdiction for complaints?', 'consumer_protection_act_2019.pdf'),
    ('What are the key features of territorial jurisdiction for complaints under the Act?', 'consumer_protection_act_2019.pdf'),
    ('What does the Act provide about pecuniary jurisdiction of consumer commissions?', 'consumer_protection_act_2019.pdf'),
    ('Which provision of the 2019 Act governs pecuniary jurisdiction of consumer commissions?', 'consumer_protection_act_2019.pdf'),
]

def collect_answer(engine, question, contexts):
    chunks = []
    for token in engine.generate_stream(question, contexts, language="English", eli5=False):
        chunks.append(token)
    return "".join(chunks).strip()

def main():
    print("=" * 70)
    print("RAG ANSWER / GROUNDEDNESS EVALUATION — 500 QUESTIONS")
    print("Candidate dataset: 250 Constitution + 250 Consumer Protection")
    print("Questions require independent review before research-paper claims.")
    print("=" * 70)
    engine = LegalRAGEngine()
    rows = []
    for i, (question, expected_source) in enumerate(TESTS, 1):
        print(f"\\n[{i:03d}/{len(TESTS)}] {question}")
        start = time.perf_counter()
        row = {"id": i, "question": question, "expected_source": expected_source,
               "predicted_domain": "", "retrieval_success": False, "source_match": False,
               "groundedness": "", "latency_seconds": "", "answer": "", "error": ""}
        try:
            contexts, retrieval_success, min_distance, predicted_domain = engine.retrieve(question)
            row["predicted_domain"] = predicted_domain
            row["retrieval_success"] = bool(retrieval_success and contexts)
            if retrieval_success and contexts:
                answer = collect_answer(engine, question, contexts)
                row["answer"] = answer
                row["groundedness"] = engine.check_groundedness(answer, contexts)
                sources = [c.get("metadata", {}).get("source", "") for c in contexts]
                row["source_match"] = expected_source in sources
            else:
                row["error"] = "Retrieval failed or returned no contexts"
        except Exception as exc:
            row["error"] = repr(exc)
        row["latency_seconds"] = round(time.perf_counter() - start, 2)
        rows.append(row)
        print("  retrieval={} source_match={} latency={}s".format(row["retrieval_success"], row["source_match"], row["latency_seconds"]))
    outdir = Path("outputs/evaluation_500_new")
    outdir.mkdir(parents=True, exist_ok=True)
    csv_path = outdir / "RAG_ANSWER_EVALUATION_500_CANDIDATE.csv"
    with csv_path.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    successful = [r for r in rows if r["retrieval_success"]]
    report_path = outdir / "RAG_ANSWER_EVALUATION_500_CANDIDATE_REPORT.txt"
    with report_path.open("w", encoding="utf-8") as f:
        f.write("RAG ANSWER EVALUATION — 500 SYNTHETIC CANDIDATE QUESTIONS\\n")
        f.write("Not an independently verified benchmark; manual review required.\\n")
        f.write(f"Total questions: {len(rows)}\\n")
        f.write(f"Retrieval success: {len(successful)}/{len(rows)} ({100*len(successful)/len(rows):.2f}%)\\n")
        f.write("Source match among successful retrievals: {:.2f}%\n".format(100 * sum(bool(r["source_match"]) for r in successful) / len(successful)) if successful else "Source match: not available\n")
        grounded = [float(r["groundedness"]) for r in successful if r["groundedness"] != ""]
        f.write(f"Average automated groundedness: {sum(grounded)/len(grounded):.2f}%\\n" if grounded else "Average groundedness: not available\\n")
        latencies = [float(r["latency_seconds"]) for r in rows]
        f.write(f"Average latency: {sum(latencies)/len(latencies):.2f}s\\n")
        f.write("Source match is not answer correctness. Review answers against authoritative source passages.\\n")
    print("\\nSaved:", csv_path)
    print("Saved:", report_path)

if __name__ == "__main__":
    main()
